---
title: "Latina/o/x Identity"
---

## Monday, January 15

NO CLASS. MLK Day.

---

## Wednesday, January 17

### Readings

1. Noe-Bustamante, Luis, Lauren Mora, and Mark Hugo Lopez. 2020. ``About One-in-Four U.S. Hispanics Have Heard of Latinx, but Just 3\% Use It.'' *Pew Research Center.* [{{< fa arrow-up-right-from-square >}}](https://www.pewresearch.org/hispanic/2020/08/11/about-one-in-four-u-s-hispanics-have-heard-of-latinx-but-just-3-use-it/)

2. **Beltrán, Cristina. 2010. "Introduction: Sleeping Giants and Demographic Floods." In *The Trouble with Unity: Latino Politics and the Creation of Identity,* 3-19. New York, NY: Oxford University Press.** {{< fa book >}}


### Discussion Questions

1. Who are we talking about when we say Hispanic or Latino/a/x? Who is included in this category?
2. Do Hispanics use the terms Latinx? If not, should they?
3. What assumption does Beltrán say is implied when Latinos are referred to as the "sleeping giant"?
4. How does Beltrán define *Latinidad*? In what ways has the process of Latinidad been helfpul and in which ways has it not?
5. What is Beltrán's central argument in her book? Do you agree or disagree? Why?




---

## Friday, January 19

### Readings 

1. Zepeda-Millán, Chris, and Sophia J. Wallace. 2013. "Racialization in Times of Contention: How Social Movements Influence Latino Racial Identity." *Politics, Groups, and Identities* 1(4): 510–27. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1080%2F21565503.2013.842492)



### For class

- [Arkansas governemnt banned the term Latinx from official documents.](https://nypost.com/2023/01/11/gov-sarah-huckabee-sanders-bans-latinx-from-arkansas-govt-docs/)


