---
title: "Latino Partisanship, Ideology, and Public Opinion"
---

## Monday, January 29

### Readings 

1. **Alvarez, R. Michael, and Lisa García Bedolla. 2003. "The Foundations of Latino Voter Partisanship: Evidence from the 2000 Election." *The Journal of Politics* 65(1): 31–49.** {{< fa file-pdf >}} available on Canvas

::: {.content-visible when-format="html"}
### Discussion Questions

1. According to Alvarez and Garcia Bedolla (2003), Latino partisanship might be more "explicitly political." What do they mean by this?
2. Why do these researchers expect Latino partisanship to be "more political"?
3. If Latino partisanship is "more political," is the psychological model of partisanship wrong?
:::


---


## Wednesday, January 31

- Campaign strategy memo workshop


---


## Friday, February 2


### Readings 

1. Gonzalez Juenke, Eric. 2016. "Viable Republicans or Fool’s Gold? The Consequences of Confusing Latino Respondents with Latino Voters." *Politics, Groups, and Identities* 4(4): 598–617. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1080%2F21565503.2015.1050419)


### Discussion Questions

1. Latinos are often seen as socially conservative. Why? Does this hold up to scrutiny? (Think about what information you need to answer this question)
2. What does the author argue in this paper?
3. The data analyzed in the paper comes from the 2006 Latino National Survey. Do you think things would look very different now, somewhat different, or about the same? Why?


- [PEW. "Hispanics and their views on social issues"](https://www.pewresearch.org/race-ethnicity/2022/09/29/hispanics-and-their-views-on-social-issues/)


---


## Monday, February 5

### Readings

1. **Bejarano, Christina E. 2014. "Latino Gender and Generation Gaps in Political Ideology." *Politics & Gender* 10(1): 62–88.** [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1017%2FS1743923X13000548)


### Discussion Questions

1. According to Bejarano (2014), what is the difference between the *modern gender gap* and the *traditional gender gap* in political ideology? In what contexts do we find each of them?
2. Is there a gender gap in ideology among Latines living in the U.S.? If so, describe it.
3. The data for this paper comes again from the 2006 Latino National Survey? Do you expect this gender gap to change? How and why?


- [Sonneland, Holly K. 2020. "How U.S. Latinos Voted in the 2020 Presidential Election." *AS/COA.*](https://www.as-coa.org/articles/chart-how-us-latinos-voted-2020-presidential-election)



 
