---
title: "Political Participation"
---


## Wednesday, February 7

### Readings 

1. Barreto, Matt A. 2010. "Assessing the Role of Shared Ethnicity in Latino Political Behavior." In *Ethnic Cues: The Role of Shared Ethnicity in Latino Political Participation,* 1-17. Ann Arbor: University of Michigan Press. (Chapter 1:  [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=nlebk&AN=350155&site=eds-live&scope=site&custid=asc1&ebv=EB&ppid=pp_1)



---


## Friday, February 9

### Readings 

1. Gutierrez, Angela, Angela X. Ocampo, Matt A. Barreto, and Gary Segura. 2019. "Somos Más: How Racial Threat and Anger Mobilized Latino Voters in the Trump Era." *Political Research Quarterly* 72(4): 960–75. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1177%2F1065912919844327)


---


## Monday, February 12

- Campaign strategy memo workshop/peer reviews

**Full draft of campaign memo due at the beginning of class on Canvas.**


---


## Wednesday, February 14

### Readings

1. Michelson, Melissa R. 2016. "Healthy Skepticism or Corrosive Cynicism? New Insights into the Roots and Results of Latino Political Cynicism." *RSF: The Russell Sage Foundation Journal of the Social Sciences* 2(3): 60–77. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.7758%2FRSF.2016.2.3.04)


---


## Friday, February 16

### Readings

1. **Hopkins, Daniel J. 2011. "Translating into Votes: The Electoral Impacts of Spanish‐Language Ballots." *American Journal of Political Science* 55(4): 814–30.** [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fwww.jstor.org%2Fstable%2F23025122)


**Campaign memo due February 16th at 11:59 pm on Canvas**
