---
title: "Historical Context"
---

## Monday, February 19

### Readings 

1. Gutiérrez, David. 1995. "Legacies of Conquest." In *Walls and Mirror,* 13-38. University of California Press. Berkeley: CA. {{< fa file-pdf >}} available on Canvas


### Review Questions

1. From class: Gutiérrez describes two views of immigration among Mexican Americans. What are they?
2. Around the time of the Mexican-American War there were two views about the Mexicans citizens that were living in the land and their assimilation into the United States. What were they?
3. How did the arrival of Anglo Americans into what was previously Mexico affect the day-to-day conditions of Mexican Americans?
4. What strategy did some Mexican Americans take to overcome discrimination coming from white Americans? How was this strategy a product of Spanish colonization of Mexico? Do we see this reflected in today's Latine community?

---


## Wednesday, February 21

### Readings

1. **Beltrán, Cristina. 2010. "El Pueblo Unido: Visions of Unity in the Chicano and Puerto Rican Movements" In *The Trouble with Unity: Latino Politics and the Creation of Identity,* 21-55. New York, NY: Oxford University Press.** {{< fa book >}}


### Discussion Questions

1. How did Chicano and Puerto Rican movements in the 60s and 70s differ in their approach from their predecessors? In other words, what strategies did previous generations of Latinos pursue in the 20s and 30s and what strategies were pursued in the 60s and 70s?
2. According to Beltrán, what are the similarities and differences between the Chicano and Puerto Ricans movements of the 60s and 70s?
3. What does it mean to *essentialize* race (or ethnicity)? What are the implications of race essentialism in a multiracial, multicultural society?
4. Do movements today reflect an *essentialist* or a *constructivist* understanding of race/ethnicity? 



---


## Friday, February 23

- No assigned reading

