---
title: "Latino/Chicano Activism"
---

## Monday, February 26

### Readings 

1. **Zepeda-Millán, Chris. 2017. *Latino Mass Mobilization: Immigration, Racialization, and Activism.* Cambridge, United Kingdom: Cambridge University Press.** (Chapter 2: "Weapons of the Not So Weak" {{< fa file-pdf >}} available on Canvas)

### Videos

[PBS. "Demonstrations of 2006."](https://gpb.pbslearningmedia.org/resource/04e09a79-4fb1-4b21-b2a9-221a180df8ae/demonstrations-of-2006/)

[PBS. "The Farm Worker Movement."](https://gpb.pbslearningmedia.org/resource/df492426-ffec-4eef-bed1-caca19c08b41/the-farm-worker-movement/)

---


## Wednesday, February 28

- Research Question and Literature workshop.



---


## Friday, March 1

### Readings 

1. Nicholls, Walter. 2013. "Undocumented, Unafraid, and Unapologetic." In *The DREAMers: How the Undocumented Youth Movement Transformed the Immigrant Rights Debate,* 118-142. Stanford, California: Stanford University Press. [{{< fa university >}}](https://search.ebscohost.com/login.aspx?direct=true&AuthType=shib&db=nlebk&AN=713555&site=eds-live&scope=site&custid=asc1&ebv=EB&ppid=pp_118)

### Discussion Questions

1. What challenges in the DREAMer movement are discussed in this chapter?
2. What do you see as a commonality between this movement and previous Latino activism? Hint: this is part of what Beltran argues in her book *The Trouble with Unity*
3. How did this movement differ from previous movements?
4. In her book, Beltran advocates for more deliberate forms of political participation and organizing. Meaning, places where people are continually talking and shaping what the group stands for.
    a. In what ways are the DREAMers an example of this?
    b. When thinking about your own advocacy (or potential advocacy), what similarities do you see between the DREAMers and other movements?



**Research question and list of literature due March 1st at 11:59 pm on Canvas.**
 
