---
title: "The Politics of Immigration"
---

## Monday, March 18

### Readings 

1. Literature Review Guide from Seattle University [{{< fa arrow-up-right-from-square >}}](https://library.seattleu.edu/c.php?g=705070&p=5006769)

### Slides

[<span class="btn btn-danger">{{< fa file-pdf >}} PDF of slides </span></p>](https://agnesscott.instructure.com/files/671667/download?download_frd=1)


---


## Wednesday, March 20

### Readings 

1. Barreto, Matt A., Sylvia Manzano, Ricardo Ramírez, and Kathy Rim. 2009. "Mobilization, Participation, and Solidaridad: Latino Participation in the 2006 Immigration Protest Rallies." *Urban Affairs Review* 44(5): 736–64. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1177%2F1078087409332925)



---


## Friday, March 22

### Readings 

1. **Pérez, Efrén O. 2015. "Xenophobic Rhetoric and Its Political Effects on Immigrants and Their Co-Ethnics." *American Journal of Political Science* 59(3): 549–64.** [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fdoi.org%2F10.1111%2Fajps.12131)
 
 
 
---


## Monday, March 25

### Readings 

1. Rouse, Stella M., Betina Cutaia Wilkinson, and James C. Garand. 2010. "Divided Loyalties? Understanding Variation in Latino Attitudes Toward Immigration." *Social Science Quarterly* 91(3): 856–82. [{{< fa university >}}](https://go.openathens.net/redirector/agnesscott.edu?url=https%3A%2F%2Fwww.jstor.org%2Fstable%2F42956434)


### Useful Links

- Pew Research Center. 2015. ["The Nation's Immigration Laws, 1920-Today"](https://www.pewresearch.org/hispanic/2015/09/28/chapter-1-the-nations-immigration-laws-1920-to-today/)
- Pew Research Center. 2015. ["U.S. Public Has Mixed Views of Immigrants and Immigration"](https://www.pewresearch.org/hispanic/2015/09/28/chapter-4-u-s-public-has-mixed-views-of-immigrants-and-immigration/)
- Pew Research Center. 2021. ["Most Latinos say U.S. immigration system needs big changes"](https://www.pewresearch.org/short-reads/2021/04/20/most-latinos-say-u-s-immigration-system-needs-big-changes/) 

---


## Wednesday, March 27

- No assigned reading.


---


## Friday, March 29

NO CLASS. Spring Holiday.


**Literature Review due March 31 at 11:59 pm on Canvas.**

